-- Ancient romance / costume-drama themed test seed data
-- Usage:
--   1. Make sure you are already using the correct database.
--   2. Run: source backend/sql/seed_ancient_romance_profiles.sql

INSERT INTO `pipeline_character_profiles` (
  `id`,
  `name`,
  `category`,
  `role`,
  `archetype`,
  `age_range`,
  `gender_presentation`,
  `description`,
  `appearance`,
  `personality`,
  `core_appearance`,
  `hair`,
  `face_features`,
  `body_shape`,
  `outfit`,
  `gear`,
  `color_palette`,
  `visual_do_not_change`,
  `speaking_style`,
  `common_actions`,
  `emotion_baseline`,
  `forbidden_behaviors`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `must_keep`,
  `forbidden_traits`,
  `aliases`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `three_view_image_url`,
  `three_view_image_path`,
  `three_view_prompt`,
  `created_at`,
  `updated_at`
) VALUES
(
  'guou_char_shen_ningwan',
  '沈宁婉',
  '古装女主',
  '女主',
  '清冷医女',
  '二十出头',
  '柔和女性化',
  '前太医院院判之女，家门获罪后隐于民间药铺，以温雅医术和极强记忆力自保。她表面克制疏冷，实则心性坚韧，一旦认定真相就绝不后退。',
  '肤色冷白，眉眼清秀锋利，黑发高束并垂细银流苏，左眼尾下有一点浅痣，身形修长，气质素净而带压迫感。',
  '清醒、忍耐、外冷内热，对局势判断极快，不轻易示弱。',
  '冷白肤色、左眼尾浅痣、黑发高束、素净清冷医女气质是核心识别。',
  '乌黑长发，高束发髻，银簪与细流苏',
  '细长凤眼，左眼尾浅痣，神情克制',
  '修长轻盈，站姿挺直，动作利落',
  '月白与浅青交叠的医女襦裙，窄袖外衫，素银腰封',
  '药囊、银针卷、薄披风',
  '月白、浅青、淡银、冷墨黑',
  '左眼尾浅痣、月白浅青服色、清冷克制神态不可改变',
  '说话平缓克制，句子短，关键处一针见血',
  '低头拈药、抬眸审视、捏紧银针、转身时衣袖轻摆',
  '常态沉静，情绪波动时也尽量压在眼神里',
  '夸张撒娇、卡通幼态、浓艳宫妆、鲜亮荧光配色、现代妆感',
  '保持古偶写实质感，不要变成仙侠夸张法术风。',
  '沈宁婉是古偶权谋线的女主医女，左眼尾浅痣、黑发高束、月白浅青衣裙是关键锚点。她聪明克制、善医善辨毒，适合诊脉、夜逃、对峙、含蓄情感镜头。',
  'ancient chinese romance heroine, calm physician woman, pale skin, black hair in high bun, subtle silver tassel hairpin, beauty mark under left eye, moon-white and pale cyan hanfu, restrained elegance, realistic costume drama',
  'same ancient romance heroine with stable face identity, beauty mark, pale cyan moon-white hanfu, controlled emotional acting, healing, running through palace corridors, confrontation under lantern light, continuity-safe movement',
  'xianxia magic aura, cartoon face, modern makeup, neon costume, exaggerated princess smile, sci-fi accessories',
  JSON_ARRAY('古偶', '医女', '女主', '权谋', '清冷'),
  JSON_ARRAY('左眼尾浅痣', '黑发高束', '月白浅青衣裙', '清冷医女气质'),
  JSON_ARRAY('夸张甜妹感', '仙侠法术特效', '浓艳大红唇', '现代饰品'),
  JSON_ARRAY('宁婉', '沈姑娘', '小沈大夫'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_char_xie_yanli',
  '谢晏离',
  '古装男主',
  '男主',
  '隐忍世子',
  '二十多岁',
  '清冷男性化',
  '靖安王府世子，外界传闻他体弱多病、无心朝局，实则暗查当年旧案。白日温雅疏淡，夜里行事凌厉，对女主既警惕又难以抽离。',
  '面容清隽，鼻梁挺直，眼尾微挑，长发半束，常着墨蓝与玄色锦袍，肩背挺拔，病弱感与威压感并存。',
  '隐忍、克制、戒备心强，对情感表达极少，但行动保护欲很重。',
  '清隽面容、墨蓝玄色锦袍、半束长发、表面病弱实则锋利是核心识别。',
  '乌发半束，玉冠固定，少量碎发垂落',
  '眼神沉静锐利，唇色偏淡，轮廓清隽',
  '高挑挺拔，肩线平直，动作克制有力',
  '墨蓝暗纹锦袍，玄色披风，玉佩压襟',
  '短匕、密信、半旧玉佩',
  '墨蓝、玄黑、冷银、暗玉青',
  '墨蓝玄色衣袍、半束长发、沉静锐利眼神不可改变',
  '低声缓语，常先停顿再下判断',
  '拢袖沉思、偏头观察、抬手护人、握紧玉佩',
  '表面温淡，危急时压迫感骤然变强',
  '霸总式油腻表白、夸张邪笑、金发、机甲化、现代西装',
  '保持古偶男主的压抑张力，不要做仙侠战神风。',
  '谢晏离是古偶男主世子，墨蓝玄色衣袍和清隽冷感面容是关键锚点。他表面病弱温雅，实则心思深沉，适合雨夜追查、护住女主、宫廷对峙和克制情感镜头。',
  'ancient chinese romance hero, noble heir, elegant but dangerous, black-blue robe, half-tied long hair, pale composed face, restrained aristocratic tension, realistic costume drama lighting',
  'same ancient romance hero with stable face and dark blue robe silhouette, restrained movement, sudden protective gestures, corridor pursuit, palace confrontation, continuity-safe emotional tension',
  'fantasy immortal lord, glowing magic armor, modern prince suit, exaggerated smirk, blond hair, cartoon proportions',
  JSON_ARRAY('古偶', '世子', '男主', '权谋', '隐忍'),
  JSON_ARRAY('墨蓝玄色锦袍', '半束长发', '清隽冷感面容', '表面病弱感'),
  JSON_ARRAY('机甲化', '仙侠战甲', '夸张邪魅笑', '现代发色'),
  JSON_ARRAY('晏离', '谢世子', '阿离'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_char_song_qinghe',
  '宋清和',
  '古装配角',
  '闺友',
  '宫廷内应',
  '二十出头',
  '柔和女性化',
  '女主幼时旧识，如今是昭华殿掌灯女官，表面温顺守礼，实际记性极好、胆子极大，暗中替女主传递宫中线索。',
  '鹅蛋脸，杏眼，发髻整洁，常穿烟粉与茶白宫装，腰间挂小铜铃香囊，气质柔和却不软弱。',
  '细腻、机警、擅长察言观色，紧张时依然能装作从容。',
  '烟粉茶白宫装、杏眼、腰间小铜铃香囊是核心识别。',
  '黑发盘成利落宫髻，簪花简洁',
  '杏眼，神情温和但眼神灵活',
  '纤细匀称，动作谨慎',
  '烟粉茶白宫装，窄袖比甲',
  '香囊、小铜铃、灯匙',
  '烟粉、茶白、浅金、木棕',
  '烟粉茶白宫装、小铜铃香囊、温和机警神态不可改变',
  '说话轻柔，常以试探句和提醒句为主',
  '整理宫灯、回头看门外、压低声音递话、轻扶裙摆快步走',
  '常态谨慎温和，紧张时眼神更快',
  '妖媚反派感、张扬艳色、现代职业装、卡通夸张表情',
  '她是古偶辅助角色，不要抢主角视觉重心，但要有辨识度。',
  '宋清和是宫廷内应型女配，烟粉茶白宫装和腰间小铜铃香囊是关键锚点。她适合递消息、夜里引路、紧张中保持镇定的宫廷过场镜头。',
  'ancient palace maid ally, soft pink and tea-white hanfu, neat palace bun, small bell sachet at waist, gentle but alert, realistic costume drama supporting role',
  'same palace maid ally with stable pink-white costume and waist sachet, quick careful steps, whispering, looking back for danger, continuity-safe palace support movement',
  'glamorous villain makeup, fantasy fairy costume, modern office wear, exaggerated comic reaction',
  JSON_ARRAY('古偶', '女配', '宫廷', '内应', '闺友'),
  JSON_ARRAY('烟粉茶白宫装', '小铜铃香囊', '温和机警神态'),
  JSON_ARRAY('妖媚浓妆', '夸张高饱和艳色', '现代服装'),
  JSON_ARRAY('清和', '宋女官', '阿和'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_char_pei_chengjin',
  '裴承瑾',
  '古装反派',
  '反派',
  '权臣公子',
  '二十多岁',
  '冷峻男性化',
  '当朝中书令之子，外表端方矜贵，实则心狠手辣，为掩埋旧案不惜步步设局。他对女主旧家案情知之甚深，也是男主最危险的对手。',
  '肤色偏冷，五官锋利，常着深绛与黑金官服，眉目压得很低，玉冠华贵但不浮夸，整体有强烈压迫感。',
  '精于算计、礼貌疏离、控制欲强，情绪越重越显得平静。',
  '深绛黑金官服、锋利眉眼、冷峻压迫感是核心识别。',
  '长发整束，黑金玉冠',
  '眉骨明显，眼神压迫，唇线锋利',
  '高瘦挺拔，姿态稳而冷',
  '深绛黑金官袍，宽袖外氅',
  '玉牌、折扇、密令',
  '深绛、黑金、冷灰、暗红',
  '深绛黑金官服、锋利眉眼、压迫感不可改变',
  '语气温雅却带命令感，喜欢把威胁说得像规劝',
  '慢慢合扇、垂眼微笑、转身离开前停一步、抬手示意拿人',
  '常态平静冷硬，真正动怒时反而更轻声',
  '热血正派感、滑稽奸笑、艳俗珠翠、现代霸总造型、仙侠魔尊特效',
  '保持古偶反派权臣气质，不要做夸张脸谱化奸臣。',
  '裴承瑾是古偶反派权臣公子，深绛黑金官服和压迫感极强的锋利眉眼是关键锚点。适合设局、宫廷审问、祭台对峙和冷静威胁镜头。',
  'ancient costume drama antagonist, elegant ruthless nobleman, dark red and black-gold robe, sharp brows, controlled menace, realistic palace intrigue style',
  'same antagonist with stable dark red official robe and sharp face identity, slow deliberate movement, quiet threat, commanding gestures, continuity-safe confrontation',
  'cartoon villain grin, demonic xianxia aura, modern suit, bright fantasy armor, exaggerated evil face',
  JSON_ARRAY('古偶', '反派', '权臣', '宫廷', '权谋'),
  JSON_ARRAY('深绛黑金官服', '锋利眉眼', '冷静压迫感'),
  JSON_ARRAY('滑稽奸臣感', '仙侠魔气', '现代西装', '夸张表情'),
  JSON_ARRAY('裴公子', '承瑾', '裴大人'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO `pipeline_scene_profiles` (
  `id`,
  `name`,
  `category`,
  `scene_type`,
  `description`,
  `story_function`,
  `location`,
  `scene_rules`,
  `time_setting`,
  `weather`,
  `lighting`,
  `atmosphere`,
  `architecture_style`,
  `color_palette`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `allowed_characters`,
  `props_must_have`,
  `props_forbidden`,
  `must_have_elements`,
  `forbidden_elements`,
  `camera_preferences`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `created_at`,
  `updated_at`
) VALUES
(
  'guou_scene_lantern_street',
  '上元灯市长街',
  '古装街市',
  '相遇场景',
  '灯火如昼的上元夜长街，花灯、纱幔、酒旗和人潮交织，适合初遇、误会、追逐与短促救援。',
  '开场',
  '京城上元灯市',
  '必须保留古代灯市的人潮、花灯和摊贩细节，不能变成现代夜市或仙侠集市。',
  '上元夜',
  '晴夜',
  '暖金灯火与局部冷月光',
  '热闹、暧昧、繁华下藏着危险',
  '盛世古都街市，飞檐木楼与彩灯长街',
  '暖金、绛红、墨蓝、浅玉白',
  '适合女主在人群中救人、男主回身相护、灯影下短暂对视。',
  '上元灯市长街是古偶男女主相遇和误会爆发的理想空间。灯火、人潮、红绸花灯和高低木楼是核心视觉锚点。',
  'ancient chinese lantern festival street, crowded market, glowing lanterns, red silk banners, wooden pavilions, warm festive lights, realistic costume drama',
  'same lantern market with stable crowd flow and lantern layout, brushing past, turning back, short chase, emotional eye contact, continuity-safe costume drama motion',
  'modern neon city, xianxia floating lanterns in sky, empty street, sci-fi bazaar, western medieval town',
  JSON_ARRAY('灯会', '上元', '长街', '相遇', '追逐'),
  JSON_ARRAY('沈宁婉', '谢晏离', '裴承瑾'),
  JSON_ARRAY('花灯', '红绸', '摊贩灯架', '人潮'),
  JSON_ARRAY('现代霓虹招牌', '悬浮法器', '玻璃幕墙'),
  JSON_ARRAY('灯火人潮', '古代摊贩', '木楼飞檐'),
  JSON_ARRAY('现代车辆', '科幻屏幕', '空旷广场'),
  JSON_ARRAY('穿行跟拍', '回身近景', '灯影中景'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_scene_medicine_courtyard',
  '雨后药铺后院',
  '古装院落',
  '疗伤场景',
  '偏僻药铺后的狭长小院，竹帘半卷，石桌上摆着药炉与银针，雨后地面微湿，适合救治、试探和克制情感推进。',
  '过渡',
  '城南药铺后院',
  '必须保留药铺院落、药炉、竹帘和雨后潮气，不能变成华丽王府花园。',
  '夜半到拂晓前',
  '雨后微凉',
  '青灰天光混合室内暖灯',
  '安静、克制、危险暂歇但疑云未散',
  '民间药铺小院，木廊、竹帘、旧石桌',
  '月白、药青、木棕、潮湿石灰色',
  '适合女主诊脉下针、男主压着伤势试探、近距离低声对话。',
  '雨后药铺后院是古偶中段情感与试探场景，药炉、竹帘、石桌和雨后微湿地面是核心环境锚点。',
  'ancient medicine courtyard after rain, bamboo curtains, stone table, herb stove, damp floor, intimate restrained costume drama realism',
  'same medicine courtyard with stable herb props and rain-wet floor, healing, whispering, cautious trust-building, continuity-safe close interaction',
  'luxury palace garden, bright modern clinic, fantasy spirit herbs glowing, empty minimalist courtyard',
  JSON_ARRAY('药铺', '后院', '疗伤', '试探', '雨后'),
  JSON_ARRAY('沈宁婉', '谢晏离'),
  JSON_ARRAY('药炉', '银针卷', '竹帘', '石桌'),
  JSON_ARRAY('现代病床', '霓虹药柜', '大面积花海'),
  JSON_ARRAY('药铺感', '雨后湿地', '低调灯火'),
  JSON_ARRAY('玻璃诊室', '仙侠灵力阵', '现代器械'),
  JSON_ARRAY('桌边近景', '半身对话', '针灸手部特写'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_scene_palace_corridor',
  '昭华殿长廊',
  '古装宫廷',
  '宫廷场景',
  '深宫长廊层层宫灯相连，红柱与纱窗延伸极深，雨丝打在廊外石阶上，适合传信、设伏、被追与骤然反转。',
  '转折',
  '昭华殿外回廊',
  '必须保留宫灯、红柱、长廊纵深和宫廷压迫感，不能变成普通宅院走廊。',
  '深夜',
  '小雨',
  '暖色宫灯与冷雨夜色对冲',
  '压抑、紧迫、秘密即将败露',
  '宫廷回廊与深宫殿宇',
  '暗红、暖金、冷黑、雨灰',
  '适合内应递信、脚步追近、男女主仓促避让与反派现身。',
  '昭华殿长廊是古偶权谋追逐场景，红柱、宫灯、长廊纵深和雨夜石阶是最关键的视觉锚点。',
  'ancient palace corridor at night, red pillars, hanging palace lanterns, deep perspective, rain outside stone steps, realistic intrigue atmosphere',
  'same palace corridor with stable lantern rhythm and red pillars, quick footsteps, secret handoff, hiding, sudden interception, continuity-safe suspense movement',
  'modern hallway, bright office corridor, xianxia crystal palace, empty minimalist gallery',
  JSON_ARRAY('宫廷', '长廊', '传信', '追逐', '转折'),
  JSON_ARRAY('沈宁婉', '谢晏离', '宋清和', '裴承瑾'),
  JSON_ARRAY('宫灯', '红柱', '纱窗', '湿石阶'),
  JSON_ARRAY('玻璃门', '电梯', '现代吊灯'),
  JSON_ARRAY('长廊纵深', '宫灯节奏', '雨夜廊外'),
  JSON_ARRAY('现代办公地毯', '赛博灯牌', '空白摄影棚'),
  JSON_ARRAY('长廊推镜', '追逐侧拍', '拦截中景'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'guou_scene_cliff_temple',
  '断崖祭庙',
  '古装高潮',
  '对峙场景',
  '建在山崖边缘的旧祭庙，残破幡旗被夜风吹动，石阶陡峭，庙中供台与火盆映出摇晃暗影，适合揭露真相、情感爆发与生死对峙。',
  '高潮',
  '京郊断崖祭庙',
  '必须保留断崖边缘、残庙、火盆和强风感，不能变成仙山大殿或平地祠堂。',
  '风夜',
  '大风',
  '火盆跳动暖光与冷色夜风光',
  '危险、决绝、情绪压到极限',
  '残破山崖祭庙，石阶古旧，幡旗破损',
  '炭黑、暗金火光、石灰白、深绛',
  '适合反派摊牌、女主举证、男主护住女主并在崖边短兵相接。',
  '断崖祭庙是古偶高潮对峙场景，断崖边、残庙火盆、强风幡旗和摇晃暗影必须稳定保留。',
  'cliffside ancient shrine at night, ruined banners, steep stone steps, braziers, strong wind, dangerous dramatic costume drama climax',
  'same cliff shrine with stable cliff edge and fire basin layout, confrontation, evidence reveal, protective movement, near-fall struggle, continuity-safe climax action',
  'bright day temple tourism spot, fantasy immortal palace, sci-fi ruin, flat courtyard without cliff',
  JSON_ARRAY('断崖', '祭庙', '对峙', '高潮', '真相'),
  JSON_ARRAY('沈宁婉', '谢晏离', '裴承瑾'),
  JSON_ARRAY('火盆', '残幡', '陡石阶', '供台'),
  JSON_ARRAY('现代护栏', '大型仙侠光阵', '旅游标识牌'),
  JSON_ARRAY('断崖边缘', '强风幡旗', '火盆暗影'),
  JSON_ARRAY('现代灯带', '平整广场', '科幻遗迹'),
  JSON_ARRAY('崖边对峙中景', '火盆反打', '近身冲突特写'),
  1,
  'seed-ancient-romance-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
);
