-- Cute cat short-film themed test seed data
-- Usage:
--   1. Make sure you are already using the correct database.
--   2. Run: source backend/sql/seed_cute_cat_profiles.sql

INSERT INTO `pipeline_character_profiles` (
  `id`,
  `name`,
  `category`,
  `role`,
  `archetype`,
  `age_range`,
  `gender_presentation`,
  `description`,
  `appearance`,
  `personality`,
  `core_appearance`,
  `hair`,
  `face_features`,
  `body_shape`,
  `outfit`,
  `gear`,
  `color_palette`,
  `visual_do_not_change`,
  `speaking_style`,
  `common_actions`,
  `emotion_baseline`,
  `forbidden_behaviors`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `must_keep`,
  `forbidden_traits`,
  `aliases`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `three_view_image_url`,
  `three_view_image_path`,
  `three_view_prompt`,
  `created_at`,
  `updated_at`
) VALUES
(
  'cute_cat_mitao',
  '蜜桃',
  '可爱猫咪',
  '主角',
  '元气冒失鬼',
  '幼年到少年感',
  '柔和女性化',
  '一只总想把每件小事都做成大冒险的奶油橘白小猫，喜欢追逐蝴蝶结、纸团和厨房里滚动的小番茄。',
  '奶油橘白相间短毛，脸圆，眼睛大而亮，尾巴末端有一圈浅橘色环纹，整体像柔软棉花糖。',
  '活泼、好奇、容易兴奋，遇到新鲜事会立刻扑上去。',
  '圆脸橘白小猫，大眼睛，尾巴末端浅橘环纹。',
  '柔软蓬松的奶油橘白短毛',
  '大圆眼，粉鼻尖，表情很灵动',
  '小巧圆润，步伐弹跳感强',
  '浅粉小围兜',
  '毛线球、小铃铛玩具',
  '奶油橘、暖白、浅粉、蜂蜜金',
  '橘白配色、圆脸、大眼睛、尾巴浅橘环纹不可改变',
  '软糯短句，惊喜感强',
  '扑跳、歪头、原地小跑、抱住玩具翻滚',
  '常态开心，惊讶时耳朵会立起',
  '阴沉冷酷、写实特工感、尖锐攻击姿态、成年壮硕体型',
  '保持可爱短片风，比例圆润，动作夸张但不要失真。',
  '蜜桃是奶油橘白小猫主角，圆脸、大眼睛和尾巴浅橘环纹是核心识别。她适合做追逐玩具、厨房探险、午后小闹剧等轻松可爱短片主角。',
  'cute fluffy orange and white kitten, round face, big sparkling eyes, soft cream fur, pink bib, playful and warm, adorable short-film style',
  'same cute orange-white kitten with stable round face and tail ring, bouncy running, playful pouncing, rolling with toys, cheerful continuity',
  'dark horror style, realistic war gear, aggressive predator look, dirty fur, human hands, sci-fi armor',
  JSON_ARRAY('可爱', '橘白猫', '主角', '元气', '短片'),
  JSON_ARRAY('圆脸', '大眼睛', '橘白配色', '尾巴环纹', '浅粉围兜'),
  JSON_ARRAY('冷酷表情', '写实战术装备', '惊悚血腥', '细长成年体型'),
  JSON_ARRAY('桃桃', '小蜜桃', 'Peachy'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_cat_naigai',
  '奶盖',
  '可爱猫咪',
  '搭档',
  '慢热饭搭子',
  '幼年到少年感',
  '中性软萌',
  '一只喜欢吃、喜欢晒太阳、看起来懒懒的奶牛猫，但关键时刻会默默帮忙，是主角最可靠的日常搭档。',
  '黑白奶牛花纹，额头有一块心形黑斑，身材圆滚滚，眼神常带一点无辜困意。',
  '慢半拍、温和、贪吃、靠谱，情绪稳定。',
  '圆滚奶牛猫，额头心形黑斑是关键辨识。',
  '顺滑黑白短毛',
  '圆圆眼，黑耳朵，额头心形黑斑',
  '小胖墩但动作不笨',
  '浅黄色口水巾',
  '小鱼干袋、软垫',
  '黑白、奶黄、柔灰',
  '奶牛花纹、额头心形斑、圆滚体型不可改变',
  '慢悠悠，句子短，尾音软',
  '慢吞吞走路、趴下打盹、叼零食、轻轻顶一下同伴',
  '常态放松，遇到食物时最有精神',
  '尖锐反派感、敏捷杀手形象、严肃特工服、苦大仇深',
  '强调治愈、柔软、可爱陪伴感。',
  '奶盖是黑白奶牛猫搭档，额头心形黑斑和圆滚体型是关键识别。他适合做吃零食、晒太阳、慢半拍跟上主角的轻喜剧镜头。',
  'cute black and white cow-pattern cat, chubby body, heart-shaped forehead patch, sleepy sweet eyes, cozy slice-of-life style',
  'same cute cow cat with stable chubby body and heart patch, waddling, napping, snack-holding, gentle buddy interaction',
  'grim realism, tactical straps, thin athletic body, villain glare, horror lighting',
  JSON_ARRAY('奶牛猫', '搭档', '贪吃', '治愈', '陪伴'),
  JSON_ARRAY('心形黑斑', '圆滚体型', '黑白奶牛花纹', '软萌状态'),
  JSON_ARRAY('锋利脸型', '冷硬武器', '黑暗反派感', '瘦高比例'),
  JSON_ARRAY('盖盖', '小奶盖', 'Milky Cap'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_cat_buding',
  '布丁',
  '可爱猫咪',
  '妹妹',
  '黏人撒娇怪',
  '幼猫',
  '柔和女性化',
  '一只总想贴着大家、喜欢钻进篮子和毛毯的小布偶猫幼崽，负责让短片气氛变得更软更甜。',
  '奶白带淡咖重点色，蓝眼睛，毛量蓬松，爪子像小棉球。',
  '黏人、爱撒娇、容易被新玩具吸引。',
  '蓝眼布偶幼猫，奶白与淡咖重点色。',
  '长而轻盈的绒毛',
  '蓝眼睛，小脸圆，神态无辜',
  '幼猫体型，小短腿，小爪子蓬松',
  '淡紫色蝴蝶结项圈',
  '小毛毯、布篮、羽毛棒',
  '奶白、淡咖、浅紫、天空蓝',
  '蓝眼、奶白淡咖配色、蓬松毛量不可改变',
  '奶声奶气，句子很短',
  '蹭来蹭去、缩成团、探头、抱住玩具不放',
  '常态依赖，开心时会轻轻踩奶',
  '凶狠表情、成人猫比例、脏乱狼狈、写实苦情',
  '保持幼猫感和毛绒感，不要转成写实成年猫。',
  '布丁是蓝眼布偶幼猫，奶白加淡咖重点色和蓬松毛量是关键识别。她适合承担撒娇、依赖、窝在篮子里、抱玩具不放的可爱镜头。',
  'adorable ragdoll kitten, fluffy cream fur with soft brown points, bright blue eyes, tiny paws, purple ribbon collar, ultra cozy cute short-film look',
  'same fluffy ragdoll kitten with stable blue eyes and soft point-color pattern, curling up, peeking out, cuddling toys, gentle cute continuity',
  'adult cat realism, war-torn mood, thin rough fur, grimdark shadows, monster expression',
  JSON_ARRAY('布偶猫', '幼猫', '撒娇', '治愈', '妹妹'),
  JSON_ARRAY('蓝眼睛', '蓬松毛量', '奶白淡咖重点色', '幼猫比例'),
  JSON_ARRAY('成年猫骨架', '冷酷脸', '重战术风', '脏乱写实'),
  JSON_ARRAY('丁丁', '小布丁', 'Pudding'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_cat_tangyuan',
  '汤圆',
  '可爱猫咪',
  '捣蛋鬼',
  '安静拆家王',
  '幼年到少年感',
  '中性活泼',
  '一只看起来安静乖巧，实际最会偷偷推倒杯子和拨动窗帘穗子的灰白小猫，适合制造轻松笑点。',
  '灰白短毛，灰色面罩花纹，鼻尖偏灰，眼睛圆，四爪白袜，尾巴蓬松。',
  '表面乖，内心好奇到停不下来，尤其喜欢偷偷试探边缘物体。',
  '灰白面罩花纹、四爪白袜、蓬松尾巴是核心视觉。',
  '灰白柔软短毛，尾巴略蓬',
  '圆眼睛，灰鼻尖，小表情很多',
  '轻快小体型，动作猫猫祟祟',
  '浅蓝小围巾',
  '纸杯、窗帘穗子、小球',
  '云灰、暖白、浅蓝',
  '灰白面罩花纹、四爪白袜、蓬松尾巴不可改变',
  '轻声嘀咕，像在自言自语',
  '悄悄拨物件、快速缩手、贴边走、装无辜',
  '平时安静，做坏事前眼神会更亮',
  '邪恶反派脸、恐怖压迫氛围、锋利肌肉线条、写实重口',
  '强调轻喜剧感和可爱捣蛋节奏。',
  '汤圆是灰白小猫捣蛋鬼，灰白面罩花纹和四爪白袜是关键识别。她适合承担轻微拆家、偷偷试探、装无辜回头看的可爱笑点镜头。',
  'cute gray and white kitten, soft mask pattern, white socks on all paws, fluffy tail, mischievous but innocent, cozy comedy short-film style',
  'same cute gray-white kitten with stable mask pattern and white socks, sneaky tapping, tiny pranks, innocent turn-back look, playful continuity',
  'violent destruction, horror expression, realistic injury, villain darkness, adult fierce cat body',
  JSON_ARRAY('灰白猫', '捣蛋', '搞笑', '轻喜剧', '短片'),
  JSON_ARRAY('灰白面罩花纹', '四爪白袜', '蓬松尾巴', '装无辜神态'),
  JSON_ARRAY('惊悚风', '夸张破坏狂', '尖锐肌肉线条', '反派压迫感'),
  JSON_ARRAY('小汤圆', '圆圆', 'Tangy'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `category` = VALUES(`category`),
  `role` = VALUES(`role`),
  `archetype` = VALUES(`archetype`),
  `age_range` = VALUES(`age_range`),
  `gender_presentation` = VALUES(`gender_presentation`),
  `description` = VALUES(`description`),
  `appearance` = VALUES(`appearance`),
  `personality` = VALUES(`personality`),
  `core_appearance` = VALUES(`core_appearance`),
  `hair` = VALUES(`hair`),
  `face_features` = VALUES(`face_features`),
  `body_shape` = VALUES(`body_shape`),
  `outfit` = VALUES(`outfit`),
  `gear` = VALUES(`gear`),
  `color_palette` = VALUES(`color_palette`),
  `visual_do_not_change` = VALUES(`visual_do_not_change`),
  `speaking_style` = VALUES(`speaking_style`),
  `common_actions` = VALUES(`common_actions`),
  `emotion_baseline` = VALUES(`emotion_baseline`),
  `forbidden_behaviors` = VALUES(`forbidden_behaviors`),
  `prompt_hint` = VALUES(`prompt_hint`),
  `llm_summary` = VALUES(`llm_summary`),
  `image_prompt_base` = VALUES(`image_prompt_base`),
  `video_prompt_base` = VALUES(`video_prompt_base`),
  `negative_prompt` = VALUES(`negative_prompt`),
  `tags` = VALUES(`tags`),
  `must_keep` = VALUES(`must_keep`),
  `forbidden_traits` = VALUES(`forbidden_traits`),
  `aliases` = VALUES(`aliases`),
  `profile_version` = VALUES(`profile_version`),
  `source` = VALUES(`source`),
  `updated_at` = NOW();


INSERT INTO `pipeline_scene_profiles` (
  `id`,
  `name`,
  `category`,
  `scene_type`,
  `description`,
  `story_function`,
  `location`,
  `scene_rules`,
  `time_setting`,
  `weather`,
  `lighting`,
  `atmosphere`,
  `architecture_style`,
  `color_palette`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `allowed_characters`,
  `props_must_have`,
  `props_forbidden`,
  `must_have_elements`,
  `forbidden_elements`,
  `camera_preferences`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `created_at`,
  `updated_at`
) VALUES
(
  'cute_scene_sun_kitchen',
  '阳光厨房角落',
  '居家日常',
  '日常场景',
  '早晨阳光照进厨房一角，木地板、餐桌腿、滚动的小番茄和软垫都在同一空间里，适合追逐和小失误喜剧。',
  '开场',
  '家中厨房',
  '必须保留暖阳、木地板和居家小物，不能变成写实工业厨房。',
  '早晨',
  '晴天',
  '暖阳自然光',
  '温暖、明亮、软乎乎、有生活气息',
  '温馨家庭厨房',
  '奶油黄、木色、浅白、番茄红',
  '适合追逐小番茄、钻桌脚、摔进软垫等可爱小闹剧。',
  '阳光厨房角落适合做可爱猫咪短片开场。暖阳、木地板、餐桌腿和滚动物件是核心视觉锚点，整体要温暖轻松。',
  'sunny cozy kitchen corner, warm sunlight, wooden floor, table legs, soft cushions, cute home props, adorable family short-film atmosphere',
  'same cozy kitchen layout with stable warm light and props, playful chasing, slipping, pouncing, cheerful cute continuity',
  'dark thriller kitchen, dirty restaurant backroom, industrial steel surfaces, horror shadows, empty warehouse',
  JSON_ARRAY('厨房', '阳光', '居家', '可爱', '日常'),
  JSON_ARRAY('蜜桃', '奶盖', '汤圆'),
  JSON_ARRAY('木地板', '阳光光斑', '软垫', '小番茄'),
  JSON_ARRAY('工业灶台', '血迹', '冷白医院灯'),
  JSON_ARRAY('暖阳', '桌脚空间', '家庭小物'),
  JSON_ARRAY('战术武器', '科幻屏幕', '恐怖阴影'),
  JSON_ARRAY('低机位跟拍', '地面追逐镜头', '近景扑跳'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_scene_balcony_garden',
  '花盆小阳台',
  '居家户外',
  '探索场景',
  '摆满小花盆和风铃的家用小阳台，地面有阳光和阴影交错，适合猫咪钻花盆、追叶子和偷看窗外小鸟。',
  '过渡',
  '家中小阳台',
  '必须保留花盆、风铃和家庭小阳台尺度，不能变成大型花园。',
  '午后',
  '晴转微风',
  '柔暖自然光',
  '轻盈、治愈、好奇心满满',
  '小户型家用阳台',
  '嫩绿、天蓝、奶白、花瓣粉',
  '适合探头看外面、被风铃吸引、绕花盆追叶子的轻松镜头。',
  '花盆小阳台是可爱探索场景，强调小尺度、家居感和风的存在。花盆、风铃、晒暖的地面是核心视觉元素。',
  'tiny home balcony garden, flower pots, wind chime, soft afternoon sun, leaves moving in breeze, adorable domestic slice-of-life',
  'same tiny balcony with stable flower-pot layout, peeking, leaf chasing, gentle stepping, cute continuity with breeze',
  'huge botanical garden, dark storm, gritty rooftop realism, empty concrete balcony, industrial scaffolding',
  JSON_ARRAY('阳台', '花盆', '午后', '治愈', '探索'),
  JSON_ARRAY('蜜桃', '布丁', '奶盖'),
  JSON_ARRAY('花盆', '风铃', '窗边靠垫', '阳光地砖'),
  JSON_ARRAY('战损铁栏杆', '暴雨雷电', '大型树林'),
  JSON_ARRAY('小阳台尺度', '风铃', '叶片摆动'),
  JSON_ARRAY('科幻设施', '黑暗工业管道', '空旷平台'),
  JSON_ARRAY('俯拍绕圈', '花盆缝隙视角', '探头特写'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_scene_blanket_fort',
  '客厅毛毯城堡',
  '居家玩乐',
  '互动场景',
  '用椅子、毛毯和抱枕搭起来的小小毛毯城堡，内部柔软昏黄，外部有客厅地毯和散落玩具，适合躲猫猫和幼猫贴贴。',
  '互动',
  '家中客厅',
  '必须保留毛毯城堡和客厅玩具感，不能变成正式帐篷露营地。',
  '傍晚',
  '室内',
  '暖黄台灯和环境光',
  '柔软、亲密、安全、童趣',
  '家庭客厅临时玩具堡垒',
  '奶油白、暖黄、柔粉、浅棕',
  '适合钻进去探头、抱枕翻倒、两只小猫贴在一起休息的镜头。',
  '客厅毛毯城堡是可爱互动场景，重点是软垫、毛毯、抱枕和狭小安全感，适合做藏猫猫和贴贴镜头。',
  'living room blanket fort, chairs covered with blankets, pillows, toys, warm lamp glow, cozy adorable kitten hideout',
  'same blanket fort with stable pillow layout, peeking, cuddling, hide-and-seek, soft playful continuity',
  'real camping tent outdoors, military bunker, dark empty room, horror tunnel, industrial warehouse',
  JSON_ARRAY('客厅', '毛毯', '躲猫猫', '贴贴', '温馨'),
  JSON_ARRAY('布丁', '奶盖', '蜜桃'),
  JSON_ARRAY('毛毯城堡', '抱枕', '玩具', '地毯'),
  JSON_ARRAY('冷白射灯', '金属床架', '室外帐篷'),
  JSON_ARRAY('毛毯垂落', '抱枕堆', '暖黄灯光'),
  JSON_ARRAY('写实战术箱', '工业铁门', '恐怖道具'),
  JSON_ARRAY('低角度探头', '城堡内部近景', '双猫中景'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cute_scene_snack_corner',
  '零食小卖部窗口',
  '街角可爱',
  '外出场景',
  '社区楼下小卖部窗口旁，摆着牛奶箱、小饼干牌和纸风车，环境小巧热闹，适合猫咪围着零食转圈和期待投喂。',
  '转场',
  '社区小卖部外侧',
  '必须保留小卖部窗口尺度和社区生活感，不能变成大型超市。',
  '下午',
  '晴天',
  '柔和日光加窗口暖灯',
  '热闹、甜甜的、轻快',
  '社区街角小卖部',
  '饼干黄、奶白、湖蓝、草莓红',
  '适合闻零食、扒窗口、围着牛奶箱转圈等轻喜剧镜头。',
  '零食小卖部窗口是轻快外出场景，重点在社区小尺度、零食诱惑和可爱期待感，画面要明亮活泼。',
  'cute neighborhood snack stall window, milk crates, cookie signs, pinwheels, bright warm daytime, adorable lively street-corner vibe',
  'same tiny snack stall scene with stable props, waiting, circling snacks, tiny hops, cheerful cute continuity',
  'large supermarket, dark alley crime scene, realistic industrial street, empty plaza, cyberpunk signage overload',
  JSON_ARRAY('零食', '小卖部', '社区', '外出', '活泼'),
  JSON_ARRAY('蜜桃', '奶盖', '汤圆'),
  JSON_ARRAY('牛奶箱', '小饼干牌', '纸风车', '窗口台面'),
  JSON_ARRAY('大型货架', '惊悚涂鸦', '战术车辆'),
  JSON_ARRAY('社区小窗口', '零食道具', '明亮氛围'),
  JSON_ARRAY('黑暗犯罪现场', '霓虹赛博广告', '巨大商超'),
  JSON_ARRAY('窗口仰拍', '围绕零食的中景', '期待特写'),
  1,
  'seed-cute-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `category` = VALUES(`category`),
  `scene_type` = VALUES(`scene_type`),
  `description` = VALUES(`description`),
  `story_function` = VALUES(`story_function`),
  `location` = VALUES(`location`),
  `scene_rules` = VALUES(`scene_rules`),
  `time_setting` = VALUES(`time_setting`),
  `weather` = VALUES(`weather`),
  `lighting` = VALUES(`lighting`),
  `atmosphere` = VALUES(`atmosphere`),
  `architecture_style` = VALUES(`architecture_style`),
  `color_palette` = VALUES(`color_palette`),
  `prompt_hint` = VALUES(`prompt_hint`),
  `llm_summary` = VALUES(`llm_summary`),
  `image_prompt_base` = VALUES(`image_prompt_base`),
  `video_prompt_base` = VALUES(`video_prompt_base`),
  `negative_prompt` = VALUES(`negative_prompt`),
  `tags` = VALUES(`tags`),
  `allowed_characters` = VALUES(`allowed_characters`),
  `props_must_have` = VALUES(`props_must_have`),
  `props_forbidden` = VALUES(`props_forbidden`),
  `must_have_elements` = VALUES(`must_have_elements`),
  `forbidden_elements` = VALUES(`forbidden_elements`),
  `camera_preferences` = VALUES(`camera_preferences`),
  `profile_version` = VALUES(`profile_version`),
  `source` = VALUES(`source`),
  `updated_at` = NOW();
