-- Cat-themed test seed data for pipeline_character_profiles and pipeline_scene_profiles
-- Usage:
--   1. Make sure you are already using the correct database.
--   2. Run: source backend/sql/seed_cat_profiles.sql

INSERT INTO `pipeline_character_profiles` (
  `id`,
  `name`,
  `category`,
  `role`,
  `archetype`,
  `age_range`,
  `gender_presentation`,
  `description`,
  `appearance`,
  `personality`,
  `core_appearance`,
  `hair`,
  `face_features`,
  `body_shape`,
  `outfit`,
  `gear`,
  `color_palette`,
  `visual_do_not_change`,
  `speaking_style`,
  `common_actions`,
  `emotion_baseline`,
  `voice_description`,
  `forbidden_behaviors`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `must_keep`,
  `forbidden_traits`,
  `aliases`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `three_view_image_url`,
  `three_view_image_path`,
  `three_view_prompt`,
  `created_at`,
  `updated_at`
) VALUES
(
  'cat_char_xuan_hujiao',
  '玄胡椒',
  '猫咪特工',
  '队长',
  '潜行指挥官',
  '成年',
  '中性偏冷',
  '一只长期活跃在旧城区屋顶线的黑猫队长，负责侦察、潜入和临场指挥，擅长在复杂环境中做出快速决策。',
  '短毛纯黑，胸口一小撮白毛，金色瞳孔，耳尖有轻微缺口，整体线条利落，气质冷静克制。',
  '冷静、审慎、控制欲强，几乎不说废话，对队友要求高但保护欲极强。',
  '纯黑短毛黑猫，金色眼睛，胸前少量白毛，耳尖小缺口，识别度强。',
  '短而贴身的黑色毛发',
  '金色竖瞳，左耳尖轻微缺损，面部锐利',
  '修长敏捷，肌肉紧实，跳跃感强',
  '深灰战术背带，小型夜行披片',
  '微型耳麦，爪套式攀爬钩，发光路线指示器',
  '黑色、深灰、冷金色',
  '黑色毛发、金色眼睛、耳尖缺口、胸前白毛不可改变',
  '低声、短句、明确指令',
  '蹲伏观察、尾巴轻摆示意、贴墙潜行、抬爪示意停下',
  '常态冷静，警戒时目光更锐利',
  '偏低沉的中性声线，干净克制，语速偏慢，咬字短促有压迫感，像随时在下达精准指令，不带明显情绪起伏。',
  '夸张搞笑、表情失控、穿鲜艳卡通服、体型突然变胖',
  '保持电影感写实动物角色，不做卡通夸张比例。',
  '玄胡椒是黑猫小队的核心指挥者，黑色短毛、金色竖瞳、胸前少量白毛和左耳尖缺口是关键识别点。性格冷静克制，说话极短，常在高处观察并用简短动作下达命令。',
  'realistic black cat captain, short black fur, golden slit pupils, small white chest tuft, chipped ear tip, tactical harness, stealth leader, cinematic lighting, grounded anatomy',
  'same black cat captain with stable facial identity and body silhouette, stealth movement, rooftop observation, precise command gestures, cinematic chase continuity',
  'cartoon style, extra limbs, human face, exaggerated smile, bright rainbow costume, low detail, blurry fur',
  JSON_ARRAY('黑猫', '队长', '潜行', '战术', '夜行'),
  JSON_ARRAY('黑色短毛', '金色竖瞳', '胸前白毛', '左耳缺口', '冷静指挥'),
  JSON_ARRAY('粉色蝴蝶结', '圆润幼态', '卡通大头', '滑稽表情'),
  JSON_ARRAY('黑队长', '椒队', 'Captain Pepper'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_char_mianhua',
  '棉花',
  '猫咪后勤',
  '医生',
  '温柔治疗者',
  '成年',
  '柔和女性化',
  '一只负责前线急救和情绪稳定的长毛白猫，常在危险行动后处理伤口、安抚队员，并保持撤离路线秩序。',
  '蓬松白色长毛，浅蓝眼睛，鼻尖淡粉，颈部围浅青色医护围巾，整体洁净柔和。',
  '温柔、坚定、有耐心，语气平缓但执行力很强。',
  '白色长毛猫，浅蓝眼睛，淡粉鼻尖，医护围巾是核心辨识。',
  '柔软蓬松的白色长毛',
  '浅蓝色眼睛，粉色鼻尖，表情温和',
  '圆润但不笨重，动作轻盈',
  '浅灰医护背带，浅青围巾，小型应急包',
  '便携医疗包，止血喷雾，小型照明灯',
  '白色、浅青色、银灰色',
  '白色长毛、蓝眼睛、浅青围巾不可改变',
  '柔和缓慢，安抚式表达',
  '整理绷带、低头检查伤口、轻拍队友肩背、稳定呼吸',
  '常态平静，危机时专注坚定',
  '温柔清透的女性化声线，音区中高但不尖，气息稳定，语速舒缓，有明显安抚感，危机时会更坚定但依旧柔和。',
  '暴躁攻击、阴狠反派表情、脏乱毛发、重金属机甲风',
  '保持写实温柔猫咪医护形象，不要夸张拟人。',
  '棉花是白色长毛猫医生，浅蓝眼睛和浅青围巾是强识别点。她负责急救和安抚，性格温柔但执行果断，适合承担救援、撤离、包扎类镜头。',
  'realistic long-haired white cat medic, pale blue eyes, soft pink nose, light cyan scarf, compact medical satchel, gentle but capable, soft cinematic realism',
  'same white cat medic with stable fur volume and face identity, bandaging, checking injuries, escorting teammates, calm rescue motion, continuity-safe medical action',
  'dirty fur, horror style, hypersexualized, cartoon mascot, oversized human hands, neon armor',
  JSON_ARRAY('白猫', '医生', '救援', '后勤', '安抚'),
  JSON_ARRAY('白色长毛', '浅蓝眼睛', '浅青围巾', '温柔气质'),
  JSON_ARRAY('暴怒表情', '暗黑血腥', '强攻击型武器', '荧光色头饰'),
  JSON_ARRAY('白医生', '小棉', 'Medic Cotton'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_char_lihuaqi',
  '狸花七',
  '猫咪侦察',
  '侦察员',
  '街区追踪者',
  '青年',
  '中性偏野',
  '一只来自旧城区街巷体系的狸花猫侦察员，熟悉市场、后巷和通风井路线，擅长跟踪目标和寻找藏匿点。',
  '棕灰黑相间狸花纹，绿色眼睛，右前爪有白袜，尾尖较深，整体野性灵巧。',
  '机警、嘴贫、反应快，面对危险时会瞬间进入高度专注状态。',
  '狸花斑纹、绿眼、右前爪白袜、深色尾尖是核心视觉。',
  '短而杂色分明的狸花毛',
  '绿色眼睛，鼻梁窄，神情机警',
  '轻快纤长，爆发力强',
  '旧皮质工具背带，斜挎侦察包',
  '微型追踪器、地图夹、便携手电',
  '棕灰、黑色、暗绿、旧铜色',
  '狸花斑纹、绿眼、右前爪白袜不可改变',
  '语速快，有街头感，偶尔带调侃',
  '回头观察、贴地快跑、钻缝隙、蹲在栏杆上嗅探',
  '平时松弛，发现线索后眼神瞬间收紧',
  '年轻灵巧的中性声线，语速快，带一点街头调侃感和机灵劲，尾音偶尔上扬，紧张时会立刻收紧变得更短更利落。',
  '高贵优雅贵族腔、过度卖萌、穿宫廷服、失去狸花纹',
  '强调写实街头侦察猫，不要幼态化。',
  '狸花七是旧城区路线专家，狸花纹、绿色眼睛和右前爪白袜是关键识别。她擅长在市场、屋顶、后巷和狭窄通道中追踪目标，动作快、机警、街头感强。',
  'realistic tabby scout cat, green eyes, white sock on right front paw, dark tail tip, urban tracker gear, agile, alert, grounded city atmosphere',
  'same tabby scout with stable stripe pattern and green eyes, rapid pursuit, sniffing clues, narrow alley movement, rooftop sprint, continuity-friendly action',
  'purebred show cat, princess accessories, childish proportions, clean fantasy palace background, blurry stripes',
  JSON_ARRAY('狸花猫', '侦察', '追踪', '旧城区', '灵活'),
  JSON_ARRAY('狸花斑纹', '绿色眼睛', '右前爪白袜', '街头侦察感'),
  JSON_ARRAY('纯白毛', '贵族礼服', '呆萌表情', '卡通线条'),
  JSON_ARRAY('阿七', '七侦察', 'Scout Seven'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_char_lanwei',
  '蓝尾',
  '猫咪技术',
  '黑客',
  '设备破解者',
  '青年',
  '中性理性',
  '一只擅长接入监控、破解门禁和干扰信号的灰蓝猫技术员，经常在行动前布置设备，在行动中远程提供路径与风险提示。',
  '灰蓝色短毛，琥珀眼，尾巴末端带冷蓝色护套，颈侧挂轻量数据终端，形象克制而精密。',
  '理性、专注、轻微强迫症，喜欢把所有步骤提前规划到位。',
  '灰蓝毛色、琥珀眼、蓝色尾部护套、数据终端是核心外观。',
  '短而顺滑的灰蓝色毛发',
  '琥珀色眼睛，神情专注，耳朵尖而立',
  '中等体型，动作精准',
  '轻量功能背心，设备挂带',
  '数据终端、微型投影器、信号干扰片',
  '灰蓝、石墨黑、冷蓝光',
  '灰蓝毛色、蓝色尾部护套、琥珀眼不可改变',
  '逻辑清晰，术语感强，句式简洁',
  '低头操作终端、抬眼校验屏幕、快速切换设备、尾巴轻轻敲地',
  '平稳克制，遇到异常会更快更短地发指令',
  '偏冷静的中性技术型声线，清晰、理性、颗粒感轻，语速中等偏快，像在持续做信息播报和风险提示，几乎没有多余语气词。',
  '热血莽撞、古风服饰、魔法特效、暖橙色大面积主色',
  '保持写实技术型猫咪，不做赛博夸张机甲。',
  '蓝尾是灰蓝短毛技术员，琥珀眼和尾巴末端蓝色护套是识别点。她负责监控接入、门禁破解和现场信息支援，动作精确，语言偏理性技术风。',
  'realistic blue-gray hacker cat, amber eyes, blue tail sleeve, compact terminal device, technical precision, cinematic practical tech aesthetic',
  'same blue-gray tech cat with stable face and tail sleeve, device operation, signal scan, terminal interaction, support-role movement continuity',
  'magic runes, giant robot body, cartoon neon overload, human keyboard hands, fantasy wizard robe',
  JSON_ARRAY('灰蓝猫', '黑客', '技术', '设备', '支援'),
  JSON_ARRAY('灰蓝短毛', '琥珀眼', '蓝色尾部护套', '技术终端'),
  JSON_ARRAY('夸张赛博机甲', '魔法阵', '霓虹爆闪', '卡通大眼'),
  JSON_ARRAY('技术尾', '蓝技师', 'Blue Tail'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_char_juwan',
  '橘丸',
  '猫咪反派',
  '盗贼',
  '狡猾收藏家',
  '成年',
  '男性化圆滑',
  '一只活跃在夜间交易网中的橘猫大盗，喜欢收集稀有鱼罐头、旧铃铛和带故事的失物，行动看似松弛，实则布局细密。',
  '橘色虎斑短毛，橙金眼，体型略壮，右脸有浅色旧疤，深酒红围巾增加辨识度。',
  '表面慵懒幽默，实则狡猾、自信、极具观察力。',
  '橘色虎斑、略壮体型、右脸浅疤、酒红围巾是核心视觉。',
  '橘色虎斑短毛',
  '橙金眼，右脸旧疤，笑意常带试探',
  '略壮但灵活，重心低',
  '酒红围巾，深色暗袋背心',
  '开锁片、小型收纳罐、旧铃铛串',
  '橘色、酒红、棕黑、旧金',
  '橘虎斑、右脸浅疤、酒红围巾不可改变',
  '轻松调侃，话里藏锋',
  '侧身回望、轻抛物件、压低身体潜行、尾巴卷起后又松开',
  '常态松弛，真正危险时笑意会收住',
  '略低的成熟男性化声线，慵懒松弛、带一点沙哑和笑意，讲话像在开玩笑但始终留着锋芒，危险时会突然压低变冷。',
  '热血正义主角、稚嫩幼猫、纯白服装、甜美偶像气质',
  '保持写实猫盗贼风格，不做可爱卡通吉祥物。',
  '橘丸是橘色虎斑盗贼，略壮体型、右脸浅疤和酒红围巾是核心识别。他擅长潜入、开锁和交易操盘，外表慵懒幽默，实际非常谨慎狡猾。',
  'realistic orange tabby thief cat, slightly stocky, orange-gold eyes, faint scar on right cheek, burgundy scarf, stealth collector aesthetic, grounded realism',
  'same orange tabby thief with stable scarf and scar, sneaking, turning back with sly expression, handling stolen items, pursuit continuity',
  'cute mascot style, overround body, clown props, bright festival costume, human smile teeth, low detail',
  JSON_ARRAY('橘猫', '盗贼', '反派', '潜入', '收藏家'),
  JSON_ARRAY('橘色虎斑', '右脸浅疤', '酒红围巾', '略壮体型'),
  JSON_ARRAY('纯善主角脸', '偶像装束', '荧光色服装', '巨大卡通头'),
  JSON_ARRAY('阿丸', '橘大盗', 'Orange Maru'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `category` = VALUES(`category`),
  `role` = VALUES(`role`),
  `archetype` = VALUES(`archetype`),
  `age_range` = VALUES(`age_range`),
  `gender_presentation` = VALUES(`gender_presentation`),
  `description` = VALUES(`description`),
  `appearance` = VALUES(`appearance`),
  `personality` = VALUES(`personality`),
  `core_appearance` = VALUES(`core_appearance`),
  `hair` = VALUES(`hair`),
  `face_features` = VALUES(`face_features`),
  `body_shape` = VALUES(`body_shape`),
  `outfit` = VALUES(`outfit`),
  `gear` = VALUES(`gear`),
  `color_palette` = VALUES(`color_palette`),
  `visual_do_not_change` = VALUES(`visual_do_not_change`),
  `speaking_style` = VALUES(`speaking_style`),
  `common_actions` = VALUES(`common_actions`),
  `emotion_baseline` = VALUES(`emotion_baseline`),
  `voice_description` = VALUES(`voice_description`),
  `forbidden_behaviors` = VALUES(`forbidden_behaviors`),
  `prompt_hint` = VALUES(`prompt_hint`),
  `llm_summary` = VALUES(`llm_summary`),
  `image_prompt_base` = VALUES(`image_prompt_base`),
  `video_prompt_base` = VALUES(`video_prompt_base`),
  `negative_prompt` = VALUES(`negative_prompt`),
  `tags` = VALUES(`tags`),
  `must_keep` = VALUES(`must_keep`),
  `forbidden_traits` = VALUES(`forbidden_traits`),
  `aliases` = VALUES(`aliases`),
  `profile_version` = VALUES(`profile_version`),
  `source` = VALUES(`source`),
  `reference_image_url` = VALUES(`reference_image_url`),
  `reference_image_path` = VALUES(`reference_image_path`),
  `reference_image_original_name` = VALUES(`reference_image_original_name`),
  `three_view_image_url` = VALUES(`three_view_image_url`),
  `three_view_image_path` = VALUES(`three_view_image_path`),
  `three_view_prompt` = VALUES(`three_view_prompt`),
  `updated_at` = NOW();


INSERT INTO `pipeline_scene_profiles` (
  `id`,
  `name`,
  `category`,
  `scene_type`,
  `description`,
  `story_function`,
  `location`,
  `scene_rules`,
  `time_setting`,
  `weather`,
  `lighting`,
  `atmosphere`,
  `architecture_style`,
  `color_palette`,
  `prompt_hint`,
  `llm_summary`,
  `image_prompt_base`,
  `video_prompt_base`,
  `negative_prompt`,
  `tags`,
  `allowed_characters`,
  `props_must_have`,
  `props_forbidden`,
  `must_have_elements`,
  `forbidden_elements`,
  `camera_preferences`,
  `profile_version`,
  `source`,
  `reference_image_url`,
  `reference_image_path`,
  `reference_image_original_name`,
  `created_at`,
  `updated_at`
) VALUES
(
  'cat_scene_rain_alley',
  '雨夜鱼铺后巷',
  '城市夜景',
  '潜入场景',
  '狭窄潮湿的旧城区后巷，墙面有鱼铺旧招牌和滴水管线，地面潮湿反光，适合潜入、跟踪和短促对峙。',
  '开场',
  '旧城区鱼铺后侧巷道',
  '镜头中必须保持狭窄巷道压迫感和潮湿反光地面，不能出现现代高楼玻璃幕墙。',
  '深夜',
  '小雨',
  '冷色路灯与店铺残余暖灯混合',
  '潮湿、紧张、带一点鱼腥和旧城生活痕迹',
  '老旧居民街区与市井后巷混合风格',
  '深蓝、湿灰、暖黄反光、铁锈红',
  '适合黑猫潜行、回头观察、尾巴掠过墙边等动作镜头。',
  '雨夜鱼铺后巷是猫咪潜入和初始追踪的理想空间。它狭窄、潮湿、冷暖混光明显，地面积水反射和旧招牌是最重要的视觉锚点。',
  'narrow wet old-city alley behind fish shop, reflective ground, dripping pipes, old signs, mixed cold street light and warm window light, realistic cinematic urban texture',
  'same alley environment with stable wet reflections, stealth movement, pursuit turns, close-quarters tension, continuity-safe urban night scene',
  'sunny daylight, modern shopping mall, purple fantasy fog, cyberpunk skyscraper, clean office corridor',
  JSON_ARRAY('雨夜', '后巷', '鱼铺', '潜入', '旧城区'),
  JSON_ARRAY('玄胡椒', '狸花七', '橘丸'),
  JSON_ARRAY('旧鱼铺招牌', '潮湿地面', '排水管', '散落木箱'),
  JSON_ARRAY('现代轿车', '商场霓虹屏', '白天阳光草地'),
  JSON_ARRAY('狭窄巷道', '地面反光', '墙边杂物', '雨滴'),
  JSON_ARRAY('高楼玻璃幕墙', '海边沙滩', '办公室工位'),
  JSON_ARRAY('低机位跟随', '转角窥视', '中近景潜行'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_scene_rooftop_chase',
  '月光屋顶连线',
  '城市高处',
  '追逐场景',
  '由连续老房屋顶、晾衣杆、水箱和窄墙脊组成的屋顶通路，适合快速奔跑、跳跃和高处对峙。',
  '追逐',
  '旧城区连续屋顶带',
  '必须强调高低落差和屋顶边缘危险感，不能变成宽阔平地。',
  '午夜',
  '多云偶见月光',
  '冷月光与远处城市散光',
  '高处、空旷、危险、速度感强',
  '旧砖房屋顶、铁皮水箱、简易加盖结构',
  '石墨蓝、冷灰、暗银、稀薄月白',
  '适合跳跃、追逐、屋脊急停和高处回望镜头。',
  '月光屋顶连线是速度型场景，重点是高低落差、窄边缘和连续跳跃路径。屋顶水箱、晾衣杆和月光切面要稳定保留。',
  'old city rooftop path, moonlit roof ridge, water tanks, hanging laundry poles, narrow edges, realistic night chase, height tension',
  'same rooftop layout with stable skyline and roof props, sprinting, leaping, sliding stop, backward glance, high-altitude continuity',
  'wide plaza, indoor hallway, bright noon sunlight, fantasy castle roof, neon hologram city',
  JSON_ARRAY('屋顶', '月光', '追逐', '跳跃', '高处'),
  JSON_ARRAY('玄胡椒', '狸花七', '橘丸'),
  JSON_ARRAY('水箱', '晾衣杆', '屋脊边缘', '远处城市灯光'),
  JSON_ARRAY('电梯厅', '写字楼玻璃走廊', '白天蓝天白云'),
  JSON_ARRAY('屋顶落差', '狭窄边缘', '月光切面'),
  JSON_ARRAY('室内吊顶', '草地公园', '大型商场广告牌'),
  JSON_ARRAY('横向跟拍', '高处俯拍', '落点特写'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_scene_bookstore_hideout',
  '旧书店密室',
  '室内据点',
  '据点场景',
  '藏在老书店深处的秘密指挥室，外面是堆叠旧书和木架，里面有地图、灯串和临时设备，是猫咪小队的分析与短暂休整地点。',
  '过渡',
  '老街书店后室',
  '必须保留旧书、木架和临时指挥设备的混合感，不能变成现代简洁办公室。',
  '深夜到凌晨',
  '室内无雨',
  '暖色台灯与局部冷光设备混合',
  '安全、隐秘、略拥挤，但仍有行动前的紧张感',
  '老木书店、窄后室、临时拼接工作区',
  '暖棕、旧纸黄、暗绿、局部冷蓝屏幕光',
  '适合角色围桌讨论、查看地图、包扎、部署下一步动作。',
  '旧书店密室是角色交流和过渡场景。旧书木架、手绘地图、暖色小灯和临时技术设备是关键视觉锚点，氛围应安全但不松懈。',
  'secret room inside old bookstore, stacked books, wooden shelves, hand-drawn maps, warm desk lamps, improvised command gear, cozy but tense realism',
  'same bookstore hideout with stable shelf layout and map desk, discussion, planning, bandaging, quiet preparation, continuity-safe indoor transition scene',
  'modern open office, minimalist white walls, sci-fi bridge, luxury hotel lobby, classroom',
  JSON_ARRAY('书店', '密室', '据点', '休整', '讨论'),
  JSON_ARRAY('玄胡椒', '棉花', '蓝尾', '狸花七'),
  JSON_ARRAY('旧书架', '地图桌', '台灯', '便携设备'),
  JSON_ARRAY('玻璃会议室', '纯白背景墙', '教室黑板'),
  JSON_ARRAY('旧书', '木架', '手绘地图', '设备线缆'),
  JSON_ARRAY('极简办公桌', '大型科幻控制台', '奢华吊灯'),
  JSON_ARRAY('环绕中景', '桌面俯拍', '角色对话近景'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_scene_morning_market',
  '清晨鱼市场装卸区',
  '市井日景',
  '混战场景',
  '天色刚亮的鱼市场装卸区，地面潮湿，冰块箱和木托盘密集，人和货物都很多，适合追踪、掩护和突发混乱。',
  '高潮前',
  '老港区鱼市场',
  '必须保留潮湿地面、鱼箱托盘和拥挤通道，不能变成空旷整洁仓库。',
  '清晨',
  '阴天',
  '自然散射冷光加作业灯',
  '忙乱、真实、拥挤、信息量大',
  '老港区批发市场与半开放装卸区',
  '灰蓝、木色、白冰、暗红工作灯',
  '适合穿梭、藏身、突然转向和大范围调度镜头。',
  '清晨鱼市场装卸区适合做复杂动线和遮挡。潮湿地面、鱼箱托盘、半开放通道和人货混杂是最重要的环境识别点。',
  'busy fish market loading area at dawn, wet ground, ice boxes, wooden pallets, narrow crowded paths, realistic industrial market atmosphere',
  'same market with stable pallet layout and wet floor, weaving through crowd, hiding, sudden turn, chaotic but readable action continuity',
  'empty warehouse, luxury restaurant, bright beach harbor, futuristic airport, shopping street mall',
  JSON_ARRAY('鱼市场', '清晨', '装卸区', '拥挤', '追踪'),
  JSON_ARRAY('狸花七', '橘丸', '玄胡椒'),
  JSON_ARRAY('鱼箱', '冰块箱', '木托盘', '半开卷帘门'),
  JSON_ARRAY('现代自动传送带', '整洁超市货架', '晴天海边沙滩'),
  JSON_ARRAY('潮湿地面', '密集货箱', '拥挤通道'),
  JSON_ARRAY('空旷机场大厅', '纯净白棚拍背景', '豪华宴会厅'),
  JSON_ARRAY('人群缝隙跟拍', '遮挡后再现身', '运动中景'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),
(
  'cat_scene_subway_tunnel',
  '废弃地铁检修通道',
  '地下空间',
  '对峙场景',
  '停用多年的地铁检修通道，墙面剥落，红色警示灯断续闪烁，地面有积水和旧电缆，适合潜伏、逼近与终局对峙。',
  '高潮',
  '旧地铁下层检修道',
  '必须保留狭长通道、红色警示灯、积水反光和旧电缆，不可变成科幻高科技隧道。',
  '深夜',
  '地下潮湿',
  '低照度冷色主光加断续红警示灯',
  '压迫、危险、即将爆发',
  '旧工业检修通道',
  '冷灰、暗蓝、警示红、湿黑',
  '适合慢速逼近、停顿对视、脚步回响和最终冲突镜头。',
  '废弃地铁检修通道是压迫型高潮场景。狭长结构、断续红灯、积水和旧电缆必须稳定保留，镜头应强调压迫和回声感。',
  'abandoned subway maintenance tunnel, peeling walls, wet reflective floor, old cables, intermittent red warning lights, realistic underground tension',
  'same tunnel with stable warning lights and wet reflections, slow approach, standoff, sudden burst action, strong continuity in narrow corridor',
  'clean sci-fi tunnel, colorful arcade, daylight station hall, futuristic spaceship corridor, white laboratory',
  JSON_ARRAY('地下', '地铁', '检修道', '对峙', '高潮'),
  JSON_ARRAY('玄胡椒', '蓝尾', '橘丸', '棉花'),
  JSON_ARRAY('红色警示灯', '旧电缆', '积水', '剥落墙面'),
  JSON_ARRAY('透明玻璃幕墙', '科幻蓝白灯带', '明亮地铁站厅'),
  JSON_ARRAY('狭长通道', '低照度', '积水反光', '红灯闪烁'),
  JSON_ARRAY('彩色游乐场', '办公室茶水间', '医院走廊'),
  JSON_ARRAY('中轴线推进', '背光剪影', '脚步特写'),
  1,
  'seed-cat-pack',
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `category` = VALUES(`category`),
  `scene_type` = VALUES(`scene_type`),
  `description` = VALUES(`description`),
  `story_function` = VALUES(`story_function`),
  `location` = VALUES(`location`),
  `scene_rules` = VALUES(`scene_rules`),
  `time_setting` = VALUES(`time_setting`),
  `weather` = VALUES(`weather`),
  `lighting` = VALUES(`lighting`),
  `atmosphere` = VALUES(`atmosphere`),
  `architecture_style` = VALUES(`architecture_style`),
  `color_palette` = VALUES(`color_palette`),
  `prompt_hint` = VALUES(`prompt_hint`),
  `llm_summary` = VALUES(`llm_summary`),
  `image_prompt_base` = VALUES(`image_prompt_base`),
  `video_prompt_base` = VALUES(`video_prompt_base`),
  `negative_prompt` = VALUES(`negative_prompt`),
  `tags` = VALUES(`tags`),
  `allowed_characters` = VALUES(`allowed_characters`),
  `props_must_have` = VALUES(`props_must_have`),
  `props_forbidden` = VALUES(`props_forbidden`),
  `must_have_elements` = VALUES(`must_have_elements`),
  `forbidden_elements` = VALUES(`forbidden_elements`),
  `camera_preferences` = VALUES(`camera_preferences`),
  `profile_version` = VALUES(`profile_version`),
  `source` = VALUES(`source`),
  `reference_image_url` = VALUES(`reference_image_url`),
  `reference_image_path` = VALUES(`reference_image_path`),
  `reference_image_original_name` = VALUES(`reference_image_original_name`),
  `updated_at` = NOW();
